"""modificaciones a la tabla assigment

Revision ID: 0c7debdc1724
Revises: 4cde3acbca6f
Create Date: 2018-09-01 16:25:11.735120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c7debdc1724'
down_revision = '4cde3acbca6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assigment', sa.Column('edit', sa.Boolean(), nullable=True))
    op.add_column('assigment', sa.Column('supervisor', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assigment', 'supervisor')
    op.drop_column('assigment', 'edit')
    # ### end Alembic commands ###
