"""add files to ticket table

Revision ID: 11113529e745
Revises: 4e7fb022fc8f
Create Date: 2019-11-27 00:15:25.451793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11113529e745'
down_revision = '4e7fb022fc8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_ticket',
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.PrimaryKeyConstraint('file_id', 'ticket_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_ticket')
    # ### end Alembic commands ###
