"""update table Priority

Revision ID: 3d2782ad21d6
Revises: 11113529e745
Create Date: 2020-01-27 23:13:44.030091

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d2782ad21d6'
down_revision = '11113529e745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('priority', 'respuesta',
               existing_type=sa.Integer(),
               nullable=False)
    op.alter_column('priority', 'resuelto',
               existing_type=sa.Integer(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('priority', 'resuelto',
               existing_type=mysql.TIME(),
               nullable=True)
    op.alter_column('priority', 'respuesta',
               existing_type=mysql.TIME(),
               nullable=True)
    # ### end Alembic commands ###
