"""remove another table

Revision ID: 4e7fb022fc8f
Revises: d53396121152
Create Date: 2019-11-21 18:44:51.341893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e7fb022fc8f'
down_revision = 'd53396121152'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('festive')
    op.drop_index('title', table_name='knowledge')
    op.drop_table('knowledge')
    op.drop_table('trophy')
    op.drop_index('title', table_name='faq')
    op.drop_table('faq')
    op.drop_table('category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('faq',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('orden', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('creado', mysql.DATETIME(), nullable=True),
    sa.Column('modificado', mysql.DATETIME(), nullable=True),
    sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='faq_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('title', 'faq', ['title'], unique=True)
    op.create_table('trophy',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('puntos', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('creado', mysql.DATETIME(), nullable=True),
    sa.Column('modificado', mysql.DATETIME(), nullable=True),
    sa.Column('file_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], name='trophy_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('knowledge',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('keys', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('creado', mysql.DATETIME(), nullable=True),
    sa.Column('modificado', mysql.DATETIME(), nullable=True),
    sa.Column('department_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('access', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('rating', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], name='knowledge_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('title', 'knowledge', ['title'], unique=True)
    op.create_table('festive',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('fecha', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
