"""cambio calendario, se creo festivos

Revision ID: 60a21aa9f17a
Revises: 8c9ccb8022fd
Create Date: 2018-03-29 16:40:27.427081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60a21aa9f17a'
down_revision = '8c9ccb8022fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('festive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar_festive',
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('festive_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendar.id'], ),
    sa.ForeignKeyConstraint(['festive_id'], ['festive.id'], ),
    sa.PrimaryKeyConstraint('calendar_id', 'festive_id')
    )
    op.drop_column(u'calendar', 'dias_festivos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'calendar', sa.Column('dias_festivos', mysql.VARCHAR(length=1024), nullable=True))
    op.drop_table('calendar_festive')
    op.drop_table('festive')
    # ### end Alembic commands ###
