"""nuevos campos en knowledges

Revision ID: 658afc498345
Revises: b5b85219cc24
Create Date: 2018-07-03 22:45:57.695748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658afc498345'
down_revision = 'b5b85219cc24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge', sa.Column('access', sa.Integer(), nullable=True))
    op.add_column('knowledge', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge', 'rating')
    op.drop_column('knowledge', 'access')
    # ### end Alembic commands ###
