"""remove calendar

Revision ID: d53396121152
Revises: fff84738f3a3
Create Date: 2019-11-21 17:34:51.506264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd53396121152'
down_revision = 'fff84738f3a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar')
    op.drop_table('calendar_festive')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_festive',
    sa.Column('calendar_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('festive_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendar.id'], name='calendar_festive_ibfk_1'),
    sa.ForeignKeyConstraint(['festive_id'], ['festive.id'], name='calendar_festive_ibfk_2'),
    sa.PrimaryKeyConstraint('calendar_id', 'festive_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('calendar',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('dias', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('hora_inicio', mysql.TIME(), nullable=True),
    sa.Column('hora_final', mysql.TIME(), nullable=True),
    sa.Column('fulltime', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
