"""cambios en ticket

Revision ID: dcc8ff814918
Revises: e67d034485f5
Create Date: 2018-07-17 20:26:41.306688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dcc8ff814918'
down_revision = 'e67d034485f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('celular', sa.String(length=12), nullable=True))
    op.add_column('ticket', sa.Column('email', sa.String(length=60), nullable=False))
    op.add_column('ticket', sa.Column('telefono', sa.String(length=30), nullable=True))
    op.alter_column('ticket', 'content',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket', 'content',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.drop_column('ticket', 'telefono')
    op.drop_column('ticket', 'email')
    op.drop_column('ticket', 'celular')
    # ### end Alembic commands ###
